version: '3.7'
services:
    wow-chat:
        build:
            context: ./
            dockerfile: ./Dockerfile
            args:
                - CONF_FILE=${CONF_FILE}
        env_file:
            - .env
